### ISSUE TITLE
Mesh to SDF Volume?

### ISSUE THREAD

**Issue by shanecranor** [quellenform/blender-geometry-nodes-overview#2]
Does the 'mesh to sdf volume' node exist?? I don't see it on blender 4.0.2

node is referenced here and a few other places on the internet
https://blenderartists.org/t/is-there-a-way-to-smooth-out-volume-to-mesh-geometry-node/1467656/2

**Comment by stephankellermayr** [comment]
@shanecranor SDF nodes were temporarily available in an alpha version, but were then removed again. You can find out more here: https://projects.blender.org/blender/blender/issues/103248
